# Develop override settings

url: http://localhost:4000

# Google Analytics
google_analytics: G-T9ZKL7KSJL

analytics:
  provider: google

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded